# http://travis-ci.org/#!/facebook/tornado
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.2
    - 3.3
env:
    - DEPS=true
    - DEPS=false
install:
    # always install unittest2 on py26 even if $DEPS is unset
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then pip install --use-mirrors futures mock pycares pycurl twisted http://pypi.python.org/packages/source/M/Monotime/Monotime-1.0.tar.gz; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DEPS == true ]]; then pip install --use-mirrors sphinx; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' && $DEPS == true ]]; then pip install --use-mirrors futures mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' && $DEPS == true ]]; then pip install --use-mirrors pycares mock; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $DEPS == true ]]; then pip install --use-mirrors pycares; fi
    - python setup.py install
script:
    # Must cd somewhere else so python3 doesn't get confused and run
    # the python2 code from the current directory instead of the installed
    # 2to3 version.
    - cd maint
    - python -m tornado.test.runtests
    - python -m tornado.test.runtests --ioloop=tornado.platform.select.SelectIOLoop
    - python -O -m tornado.test.runtests
    - LANG=C python -m tornado.test.runtests
    - LANG=en_US.utf-8 python -m tornado.test.runtests
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -bb -m tornado.test.runtests; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy && $DEPS == true ]]; then python -m tornado.test.runtests --resolver=tornado.netutil.ThreadedResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python -m tornado.test.runtests --httpclient=tornado.curl_httpclient.CurlAsyncHTTPClient; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python -m tornado.test.runtests --ioloop_time_monotonic; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python -m tornado.test.runtests --ioloop=tornado.platform.twisted.TwistedIOLoop; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DEPS == true ]]; then python -m tornado.test.runtests --resolver=tornado.platform.twisted.TwistedResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION != pypy && $DEPS == true ]]; then python -m tornado.test.runtests --resolver=tornado.platform.caresresolver.CaresResolver; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then python -m tornado.test.runtests --ioloop_time_monotonic; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $DEPS == true ]]; then cd ../docs && mkdir sphinx-out && sphinx-build -E -n -W -b html . sphinx-out; fi
